print('Tabuada')
n = int(input('Digite o número da tabuada desejada: '))
a = int(1 * n)
b = int(2 * n)
c = int(3 * n)
d = int(4 * n)
e = int(5 * n)
f = int(6 * n)
g = int(7 * n)
h = int(8 * n)
i = int(9 * n)
j = int(10 * n)
print('Resultado:')
print('1 * {} = {}'.format(n,a))
print('2 * {} = {}'.format(n,b))
print('3 * {} = {}'.format(n,c))
print('4 * {} = {}'.format(n,d))
print('5 * {} = {}'.format(n,e))
print('6 * {} = {}'.format(n,f))
print('7 * {} = {}'.format(n,g))
print('8 * {} = {}'.format(n,h))
print('9 * {} = {}'.format(n,i))
print('10 * {} = {}'.format(n,j))
